Re-implement LM rescore for online transducer
k2-fsa/sherpa-onnx pull request #1231
Opened 2024-08-07 10:43 UTC by SilverSulfide

Shallow fusion can be too slow for online cpu inference. Added an option to use classical LM rescore instead.

- Rescore implementation based on https://github.com/k2-fsa/sherpa-onnx/pull/133
- Shallow fusion enabled by default
- Pass _lm-shallow-fusion=false_ to enable rescore instead
- Updated online Python API

CPU runtime comparison for ~1 min wav file using the default _--lm-num-threads=1_

| Method              | Runtime (s) | RTF |
| :---------------- | :------: | :----: |
| No LM | 5.7  | 0.098 |
| Rescore | 40 | 0.68 |
| Shallow Fusion | 69 | 1.2 |

2024-08-12 14:40 UTC, csukuangfj requested changes

2024-08-12 14:40 UTC, csukuangfj commented on sherpa-onnx/csrc/online-lm-config.cc
> +  os << "shallow_fusion=\"" << (shallow_fusion ? "True" : "False") << "\")";
```suggestion
  os << "shallow_fusion=" << (shallow_fusion ? "True" : "False") << ")";
```

We use `""` only for string variables.

2024-08-12 14:40 UTC, csukuangfj commented on sherpa-onnx/python/sherpa_onnx/online_recognizer.py
>              scale=lm_scale,
Please also update
https://github.com/k2-fsa/sherpa-onnx/blob/5f9441bfdb2cc4d2a6076ac8be5e37a59f85f9fe/sherpa-onnx/python/csrc/online-lm-config.cc#L18

2024-09-03 10:49 UTC, SilverSulfide commented
@csukuangfj hi, are there any more changes that should be written?

2024-09-03 10:55 UTC, csukuangfj commented
Could you fix the CI errors for Python?

2024-09-05 07:30 UTC, SilverSulfide commented
@csukuangfj should be resolved now!

2024-09-06 02:01 UTC, merged