JNI Exception Handling
k2-fsa/sherpa-onnx pull request #1452
Opened 2024-10-21 18:32 UTC by iprovalo

JNI Exception Handling.  Throw Java RuntimeException and let the client deal with it.  The advantage of this approach is that a client may decide to show a different message to the user.

2025-02-14 15:51 UTC, iprovalo commented
@csukuangfj would you consider merging this PR?  This is related to [JNI discussion](https://github.com/k2-fsa/sherpa-onnx/discussions/1426).

The justification is that there could be some unforeseen conditions causing the data to become corrupt, or a device type compatibility issue with any of the underlying native libraries, causing a crash.  JNI layer exception handling allows to delegate the exception handling to the UI and add some useful messages for the user to react to it by reinstalling the app in case if this behavior continues.  

I have noticed a significant drop in crashes when I rolled these out to a few hundred devices.

2025-02-15 12:16 UTC, csukuangfj requested changes

2025-02-15 12:16 UTC, csukuangfj commented on sherpa-onnx/jni/voice-activity-detector.cc
> +    model->Reset();
It is hard to imagine that this function can throw.

Could you post the exception messages?

2025-02-15 12:16 UTC, csukuangfj commented on sherpa-onnx/jni/offline-recognizer.cc
> +                      "OfflineRecognizer pointer is null.");
Can you write a function to throw an exception so that a lot of duplicate code is reduced to call that function.

2025-02-15 16:23 UTC, iprovalo commented on sherpa-onnx/jni/voice-activity-detector.cc
> +    model->Reset();
There is not much in the exception log right now, beside this:

#00  pc 0x0000000000090480  /data/app/~~OPsl1ZjlmW-J2qp-_4TVtA==/com.lingofonex.android-VkSxvfpHKGKaQ2dvrt-dEw==/split_config.arm64_v8a.apk!libsherpa-onnx-jni.so (Java_com_k2fsa_sherpa_onnx_Vad_reset+16) (BuildId: df851e8489be509b8a09d60eab3ba57ea3ff5786)

While these exceptions are below 2%, they are still hurting the metrics significantly.  I deployed debug symbols in my latest release, if I get any more data pointing to specific code area, I will share.  For now, I am trying to handle these in the JNI, and try to recover the UI without a crash.

2025-02-15 16:27 UTC, iprovalo commented on sherpa-onnx/jni/offline-recognizer.cc
> +                      "OfflineRecognizer pointer is null.");
Yes, good point, let me do that!

2025-02-15 20:36 UTC, iprovalo commented on sherpa-onnx/jni/offline-recognizer.cc
> +                      "OfflineRecognizer pointer is null.");
Updated.

2025-02-19 07:27 UTC, csukuangfj commented
Is it ready for merge?

2025-02-19 14:08 UTC, iprovalo commented
> Is it ready for merge?

Yes, this is ready to merge.

2025-02-19 15:01 UTC, csukuangfj commented
Thank you for your contribution!

2025-02-19 15:02 UTC, merged