Add C / Python API for keyword spotting
k2-fsa/sherpa-onnx pull request #576
Opened 2024-02-07 03:46 UTC by pkufool

2024-02-28 11:49 UTC, csukuangfj requested changes

2024-02-28 11:49 UTC, csukuangfj commented on python-api-examples/keyword-spotter-from-microphone.py
> +        The file containing keywords, one words/phrases per line, and for each
```suggestion
        The file containing keywords, one word/phrase per line, and for each
```

2024-02-28 11:49 UTC, csukuangfj commented on python-api-examples/keyword-spotter-from-microphone.py
> +        default="",
```suggestion
```

It cannot be empty.

2024-02-28 11:49 UTC, csukuangfj commented on python-api-examples/keyword-spotter-from-microphone.py
> +    )
```suggestion
```

2024-02-28 11:49 UTC, csukuangfj commented on python-api-examples/keyword-spotter.py
> +        default="",
```suggestion
```

2024-02-28 11:49 UTC, csukuangfj commented on sherpa-onnx/python/sherpa_onnx/keyword_spotter.py
> +    """A class for streaming speech recognition.
```suggestion
    """A class for streaming keyword spotting.
```

2024-02-28 11:49 UTC, csukuangfj commented on sherpa-onnx/python/sherpa_onnx/keyword_spotter.py
> +            feat_config,
Please use 
```
key=value
```
for this function.

2024-02-28 11:49 UTC, csukuangfj commented on sherpa-onnx/python/sherpa_onnx/keyword_spotter.py
> +        keywords_file: str = "",
Is `keywords_file` allowed to be empty?

I see that you check its existence explicitly in the example.

If it is not allowed to be empty, please don't use a default empty value for it.

2024-03-01 01:31 UTC, merged

2024-03-01 08:21 UTC, lonngxiang commented
@pkufool  非常感谢；这里有个单词拼写错了https://github.com/k2-fsa/sherpa-onnx/issues/621